# SPDX-License-Identifier: AGPL-3.0-or-later

import Config

# Configure your database
if System.fetch_env!("SIKIO_DATABASE") == "sqlite" do
  config :sikio, Sikio.Repo,
    database: Path.expand("../tmp/sikio_dev.db", __DIR__),
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 5
else
  config :sikio, Sikio.Repo,
    username: System.get_env("PGUSER", "postgres"),
    password: System.get_env("PGPASSWORD", "postgres"),
    hostname: System.get_env("PGHOST", "localhost"),
    port: String.to_integer(System.get_env("PGPORT", "5432")),
    database: "sikio_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sikio, SikioWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # PORT is an override for running beside another Phoenix application; the default stays 4000.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT", "4000"))],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "58wQvTrKhh7Q4G5s6XNlBjVrxhoB/9rw/Fk9Zh5zmxRRwZSZw3x8hjN5eYVl+CCS",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sikio, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sikio, ~w(--watch)]}
  ]

# A phone reaches the development server through a tunnel such as `tailscale serve`. Passkeys
# are bound to the host the endpoint names, so SIKIO_DEV_URL gives it the tunnel's address.
case "SIKIO_DEV_URL" |> System.get_env("") |> String.trim() do
  "" ->
    :ok

  address ->
    case URI.parse(address) do
      %URI{scheme: "https", host: host, port: port} when is_binary(host) and host != "" ->
        config :sikio, SikioWeb.Endpoint, url: [scheme: "https", host: host, port: port]

      _other ->
        raise "SIKIO_DEV_URL must be an https address such as https://mac.tailnet.ts.net, " <>
                "not #{inspect(address)}"
    end
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Delivered to the local mailbox rather than to anybody, and counted as configured, so that
# ACCOUNT_IDENTITY=email can be run in development without a submission server. Setting
# MAIL_ENABLED in the environment replaces both at runtime.
config :sikio, Sikio.Mailer, adapter: Swoosh.Adapters.Local
config :sikio, :mail_enabled, true
config :sikio, :mail_from, {"Sikio", "sikio@localhost"}

# Pictures fetched from publishers, kept beside the project rather than in the release.
config :sikio, picture_cache_dir: Path.expand("../tmp/pictures", __DIR__)

# A development server is not reachable from the internet, so it asks no hub to subscribe.
config :sikio, :websub, false
