# SPDX-License-Identifier: AGPL-3.0-or-later

import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sikio, SikioWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :sikio, SikioWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# No access log: Phoenix's lines for requests and sockets name what a member opened, and its
# socket lines carry the player's session. A proxy logs access if wanted. Crashes are still
# logged. The level and the JSON format are set in config/runtime.exs; see Sikio.Logging.
config :phoenix, :logger, false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
