# SPDX-License-Identifier: AGPL-3.0-or-later

defmodule SikioWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :sikio

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_sikio_key",
    signing_salt: "PxukINKI",
    same_site: "Lax",
    encryption_salt: "mNqjztHi9zI12aLG"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  if Application.compile_env(:sikio, :sql_sandbox, false) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Tests turn it off: a release build leaves compressed copies
  # that are older than the assets the tests just built.
  plug Plug.Static,
    at: "/",
    from: :sikio,
    gzip: Application.compile_env(:sikio, :gzip_static, not code_reloading?),
    only: SikioWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if Application.compile_env(:sikio, :dev_routes, false) do
    plug Tidewave
  end

  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :sikio
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Before the request id and the telemetry, so a log line names the visitor rather than the proxy
  # that carried them.
  plug SikioWeb.ClientIp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SikioWeb.Router
end
